name: Projeto Desafio-Security CI

on:
  push:
    branches:
      - main
      - desafio-teste
  pull_request:
    branches:
      - main
      - desafio-teste

jobs:
  build:
    name: Build do Projeto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
   
      - name: Build do Docker
        run: |
          docker build -t app:ci .

      - name: Rodar testes
        run: |
          docker run ---rm app:ci python -m pytest -q test_app.py

  docker-publish:
    name: Publicar Docker Imagem
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da Imagem Docker
        run: |
          docker build -t jugalvaomiyaki/desafio-security:latest .
          docker push jugalvaomiyaki/desafio-security:latest
      
